//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Client.rc
//
#define IDR_MS_OK                       1
#define IDD_ABOUTBOX                    100
#define IDR_WINDOW_LIST                 101
#define IDS_TITLE                       102
#define IDD_MAP_DIALOG                  102
#define IDI_MGICON_A                    113
#define IDI_MGICON_C                    114
#define IDI_MGICON_D                    115
#define IDI_MGICON_E                    116
#define IDI_MGICON_F                    117
#define IDI_MGICON_G                    119
#define IDI_SYSICO_001                  121
#define IDI_SYSICO_002                  122
#define IDI_ICOS1                       123
#define IDI_SYSICO_003                  123
#define IDI_SYSICO_004                  124
#define IDI_ICONSERT0                   127
#define IDR_MAINFRAME                   128
#define IDR_ClientTYPE                  129
#define IDI_SYSICO_005                  129
#define IDI_SYSICO_006                  130
#define IDD_BUILD                       131
#define IDR_MENU_REPORT                 131
#define IDI_SYSICO_007                  131
#define IDD_FILE                        132
#define IDI_SYSICO_008                  132
#define IDR_LIST                        133
#define IDI_SYSICO_009                  133
#define IDC_DRAG                        134
#define IDI_SYSICO_010                  134
#define IDC_MUTI_DRAG                   135
#define IDC_CURSOR3                     136
#define IDC_CURSOR4                     137
#define IDI_ICONSERT2                   137
#define IDD_START                       137
#define IDD_SETTINGS                    140
#define IDD_UPDATE_DLG                  144
#define IDR_FILEMANAGER                 146
#define IDR_TOOLBAR1                    147
#define IDB_TOOLBAR                     149
#define IDB_TOOLBAR_ENABLE              149
#define IDR_TOOLBAR2                    154
#define IDI_ICON_L2                     154
#define IDD_DIALOG_PRANK                154
#define IDR_LOCAL_VIEW                  156
#define IDR_REMOTE_VIEW                 157
#define IDB_TOOLBAR_DISABLE             158
#define IDD_TRANSFERMODE_DLG            159
#define IDD_SCREENSPY                   160
#define IDD_DOWNEXEC                    162
#define IDD_WEBCAM                      163
#define IDI_WEBCAM                      164
#define IDB_ARROWDOWN                   165
#define IDB_ARROWUP                     166
#define IDD_KEYBOARD                    167
#define IDD_NEWFOLDER                   168
#define IDD_SYSTEM                      169
#define IDR_PSLIST                      170
#define IDD_SHELL                       171
#define IDR_BSS                         173
#define IDI_CMDSHELL                    177
#define IDI_KEYBOARD                    178
#define IDI_SYSTEM                      179
#define IDC_DOT                         182
#define IDC_DELKEY                      182
#define IDR_MINIMIZE                    183
#define IDD_AUDIO                       184
#define IDI_AUDIO                       185
#define IDD_SYSINFO                     186
#define IDD_SERMANA                     187
#define IDI_IPS                         187
#define IDB_FILE                        188
#define IDR_SLIST                       188
#define IDI_OS                          188
#define IDB_PINGMU                      189
#define IDI_CPU                         189
#define IDD_DDOS                        189
#define IDD_LOGIN                       189
#define IDB_KEYBOARD                    190
#define IDI_MEMORY                      190
#define IDD_LOCK                        190
#define IDB_CMDSHELL                    191
#define IDD_CHANGE_GROUP                191
#define IDI_DISK                        191
#define IDB_SYSTEM                      192
#define IDI_USERNAME                    192
#define IDB_AUDIO                       193
#define IDI_TIME                        193
#define IDR_LOG                         193
#define IDB_WEBCAM                      194
#define IDD_SERVICE                     194
#define IDR_ADSL_COPY                   194
#define IDB_SERVICE                     195
#define IDR_SSLIST                      195
#define IDD_DDOSZDY                     195
#define IDC_SAVEKEY                     195
#define IDB_REGEDIT                     196
#define IDI_DOUBLE                      196
#define IDB_BIND                        197
#define IDB_SETTING                     198
#define IDB_UPDATE                      199
#define IDB_BUILD                       200
#define IDB_ABOUT                       201
#define IDI_ICON_TOOL                   201
#define IDD_SIGNATURE                   201
#define IDB_EXIT                        202
#define IDD_ATTACK_DIALOG               202
#define IDI_ICON_MD5                    202
#define IDR_QQxuanwu                    202
#define IDI_STR_ICON                    203
#define IDD_IPUPDATE                    203
#define IDR_360weishi                   203
#define IDI_DWORD_ICON                  204
#define IDD_CUSTOMATTACK_DIALOG         204
#define IDR_kugou                       204
#define IDI_REG_ICON                    205
#define IDI_ICOINFO_PROCESS             205
#define IDR_liulanqi                    205
#define IDD_REG_DIALOG                  206
#define IDI_SER_ICON                    206
#define IDI_ICOINFO_APPWIN              206
#define IDR_SLIST1                      206
#define IDR_xunlei                      206
#define IDI_DIR_ICON                    207
#define IDR_tengxun                     207
#define IDI_FATHER_ICON                 208
#define IDI_ICON_DIALU                  208
#define IDD_CHECK_PASS                  208
#define IDI_ONLINE                      210
#define IDR_REGT_MENU                   211
#define IDD_SETTING                     211
#define IDD_REGDATA_DLG                 212
#define IDR_REGL_MENU                   213
#define IDD_BIND                        213
#define IDB_SPLASH                      214
#define IDD_PLAY                        215
#define IDR_UPX                         216
#define IDR_FSG                         217
#define IDD_MIANZE_DIALOG               218
#define IDI_SHIPIN                      219
#define IDI_USER                        220
#define IDR_TXT                         220
#define IDD_UPDATE                      224
#define IDR_TOOLBAR3                    224
#define IDD_INSTALL                     225
#define IDR_WLIST                       226
#define IDR_ILIST                       227
#define IDI_ICOFILE                     227
#define IDD_TOOLS_DIALOG                227
#define IDI_ANTI                        228
#define IDR_MENU1                       228
#define IDR_TOOLBAR4                    229
#define DI_SYSKM                        230
#define IDI_SYSKM                       230
#define IDB_BARNEW                      231
#define IDI_FATHER_ICON1                231
#define IDI_ICON_NET                    232
#define IDR_SKIN                        233
#define IDI_REG_ICON1                   233
#define IDD_MSGBOX                      234
#define IDR_RTF                         235
#define IDI_UPDLL                       236
#define IDB_BAR                         237
#define IDD_PROXY                       238
#define IDD_SHORTCUTS                   239
#define IDD_FLOWATTACK_DIALOG           240
#define IDD_DIALOG_PROXY_MAP            245
#define IDI_SHENGMING                   247
#define IDI_XIAXIAN                     248
#define IDI_JIANTINGCHENGGONG           249
#define IDI_JIANTINGSHIBAI              250
#define IDB_MENU1                       251
#define IDI_SHANGXIAN                   251
#define IDB_MENU2                       252
#define IDI_CHONGFUSHANGXIAN            252
#define IDB_MENU3                       253
#define IDI_ICON1                       254
#define IDB_MENU4                       254
#define IDI_ICON2                       255
#define IDB_MENU5                       255
#define IDI_ICON3                       256
#define IDB_MENU6                       256
#define IDI_ICON4                       257
#define IDI_ICON5                       258
#define IDI_ICON6                       259
#define IDI_ICON7                       260
#define IDI_ICON8                       261
#define IDI_ICON9                       262
#define IDI_ICON10                      263
#define IDR_TabCtrl                     263
#define IDI_ICON11                      264
#define IDI_ICON12                      265
#define IDI_ICON13                      266
#define IDI_ICON14                      267
#define IDI_ICON15                      268
#define IDI_ICON16                      269
#define IDI_ICON17                      270
#define IDI_ICON18                      271
#define IDI_ICON19                      272
#define IDI_ICON20                      273
#define IDI_ICON21                      274
#define IDI_ICON22                      275
#define IDI_ICON23                      276
#define IDI_ICON24                      277
#define IDI_ICON25                      278
#define IDI_ICON26                      279
#define IDI_ICON27                      280
#define IDI_ICON28                      281
#define IDI_ICON29                      282
#define IDI_ICON30                      283
#define IDI_ICON31                      284
#define IDI_ICON32                      285
#define IDI_ICON33                      286
#define IDI_ICON34                      287
#define IDI_ICON35                      288
#define IDI_ICON36                      289
#define IDI_ICON37                      290
#define IDI_ICON38                      291
#define IDI_ICON39                      292
#define IDI_ICON40                      293
#define IDI_ICON41                      294
#define IDI_ICON42                      295
#define IDI_ICON43                      296
#define IDI_ICON44                      297
#define IDI_ICON45                      298
#define IDI_ICON46                      299
#define IDI_ICON47                      300
#define IDI_ICON48                      301
#define IDI_ICON49                      302
#define IDI_ICON50                      303
#define IDI_ICON51                      304
#define IDI_ICON52                      305
#define IDI_ICON53                      306
#define IDI_ICON54                      307
#define IDI_ICON55                      308
#define IDI_ICON56                      309
#define IDI_ICON57                      310
#define IDI_ICON58                      311
#define IDI_ICON59                      312
#define IDI_ICON60                      313
#define IDI_ICON61                      314
#define IDI_ICON62                      315
#define IDI_ICON63                      316
#define IDI_ICON64                      317
#define IDI_ICON65                      318
#define IDI_ICON66                      319
#define IDI_ICON67                      320
#define IDI_ICON68                      321
#define IDI_ICON69                      322
#define IDI_ICON70                      323
#define IDI_ICON71                      324
#define IDI_ICON72                      325
#define IDR_WAVE1                       325
#define IDI_ICON73                      326
#define IDR_WAVE2                       326
#define IDI_ICON74                      327
#define IDR_WAVE3                       327
#define IDI_ICON75                      328
#define IDI_ICON76                      329
#define IDI_ICON77                      330
#define IDI_ICON78                      331
#define IDI_ICON79                      332
#define IDI_ICON80                      333
#define IDI_ICON81                      334
#define IDI_ICON82                      335
#define IDI_ICON83                      336
#define IDI_ICON84                      337
#define IDI_ICON85                      338
#define IDI_ICON86                      339
#define IDI_ICON87                      340
#define IDI_ICON88                      341
#define IDC_STOP2                       341
#define IDI_ICON89                      342
#define IDI_ICON90                      343
#define IDI_ICON91                      344
#define IDI_ICON92                      345
#define IDI_ICON93                      346
#define IDI_ICON94                      347
#define IDI_ICON95                      348
#define IDI_ICON96                      349
#define IDI_ICON97                      350
#define IDI_ICON98                      351
#define IDI_ICON99                      352
#define IDD_DLLDLG                      353
#define IDI_ICON100                     353
#define IDI_ICON101                     354
#define IDD_CHAT                        354
#define IDI_ICON102                     355
#define IDD_PLAYER                      355
#define IDD_PLAYER_DIALOG               355
#define IDI_ICON103                     356
#define IDI_ICON104                     357
#define IDI_ICON105                     358
#define IDI_ICON106                     359
#define IDI_ICON107                     360
#define IDI_ICON108                     361
#define IDI_ICON109                     362
#define IDI_ICON110                     363
#define IDI_ICON111                     364
#define IDI_ICON112                     365
#define IDI_ICON113                     366
#define IDI_ICON114                     367
#define IDI_ICON115                     368
#define IDI_ICON116                     369
#define IDI_ICON117                     370
#define IDI_ICON118                     371
#define IDI_ICON119                     372
#define IDI_ICON120                     373
#define IDI_ICON121                     374
#define IDI_ICON122                     375
#define IDI_ICON123                     376
#define IDI_ICON124                     377
#define IDI_ICON125                     378
#define IDI_ICON126                     379
#define IDI_ICON127                     380
#define IDI_ICON128                     381
#define IDI_ICON129                     382
#define IDI_ICON130                     383
#define IDI_ICON131                     384
#define IDI_ICON132                     385
#define IDI_ICON133                     386
#define IDI_ICON134                     387
#define IDI_ICON135                     388
#define IDI_ICON136                     389
#define IDI_ICON137                     390
#define IDI_ICON138                     391
#define IDI_ICON139                     392
#define IDI_ICON140                     393
#define IDI_ICON141                     394
#define IDI_ICON142                     395
#define IDI_ICON143                     396
#define IDI_ICON144                     397
#define IDI_ICON145                     398
#define IDI_ICON146                     399
#define IDI_ICON147                     400
#define IDI_ICON148                     401
#define IDI_ICON149                     402
#define IDI_ICON150                     403
#define IDI_ICON151                     404
#define IDI_ICON152                     405
#define IDI_ICON153                     406
#define IDI_ICON154                     407
#define IDI_ICON155                     408
#define IDI_ICON156                     409
#define IDI_ICON157                     410
#define IDI_ICON158                     411
#define IDI_ICON159                     412
#define IDI_ICON160                     413
#define IDI_ICON161                     414
#define IDI_ICON162                     415
#define IDI_ICON163                     416
#define IDI_ICON164                     417
#define IDI_ICON165                     418
#define IDI_ICON166                     419
#define IDI_ICON167                     420
#define IDI_ICON168                     421
#define IDI_ICON169                     422
#define IDI_ICON170                     423
#define IDI_ICON171                     424
#define IDI_ICON172                     425
#define IDI_ICON173                     426
#define IDI_ICON174                     427
#define IDI_ICON175                     428
#define IDI_ICON176                     429
#define IDI_ICON177                     430
#define IDI_ICON178                     431
#define IDI_ICON179                     432
#define IDI_ICON180                     433
#define IDI_ICON181                     434
#define IDI_ICON182                     435
#define IDI_ICON183                     436
#define IDI_ICON184                     437
#define IDI_ICON185                     438
#define IDI_ICON186                     439
#define IDI_ICON187                     440
#define IDI_ICON188                     441
#define IDI_ICON189                     442
#define IDI_ICON190                     443
#define IDI_ICON191                     444
#define IDI_ICON192                     445
#define IDI_ICON193                     446
#define IDI_ICON194                     447
#define IDI_ICON195                     448
#define IDI_ICON196                     449
#define IDI_ICON197                     450
#define IDI_ICON198                     451
#define IDI_ICON199                     452
#define IDI_ICON200                     453
#define IDI_ICON201                     454
#define IDI_ICON202                     455
#define IDI_ICON203                     456
#define IDI_ICON204                     457
#define IDI_ICON205                     458
#define IDI_ICON206                     459
#define IDI_ICON207                     460
#define IDI_ICON208                     461
#define IDI_EVENT_INFO                  462
#define IDI_EVENT_ERROR                 463
#define IDI_BE_CAREFUL                  464
#define IDI_zhuji                       465
#define IDI_shuj                        466
#define IDI_send                        466
#define IDI_duanko                      467
#define IDI_shangx                      469
#define IDI_WEL_COME                    488
#define IDI_reci                        490
#define IDI_ICONSERT1                   491
#define IDD_TEST                        513
#define IDI_ICON_SOFT                   515
#define IDI_NETWORK                     516
#define IDB_MENU7                       541
#define IDB_BITMAP1                     543
#define IDI_ICON_L3                     569
#define IDI_ICON_L4                     571
#define IDI_ICON_L1                     572
#define IDI_Start                       592
#define IDI_Delete                      593
#define IDI_Add                         594
#define IDI_stop                        596
#define IDI_SYSTRAY1                    597
#define IDB_SHOWMSG                     607
#define IDC_HAND_1                      608
#define IDD_LockFile                    627
#define IDI_QQ                          673
#define IDI_ICON_QQ                     676
#define IDI_File                        680
#define IDI_Build                       682
#define IDI_SHELL                       685
#define IDI_SCREEN                      686
#define IDI_SETTING                     688
#define IDI_SERT                        691
#define IDI_SYSINFO                     692
#define IDI_MAP                         693
#define IDI_ICONEXE                     708
#define IDI_ICONTOOL                    709
#define IDI_PRANK                       722
#define IDR_BAIDU                       725
#define IDR_BAIDUE                      726
#define IDR_GAODE                       727
#define IDR_GAODEE                      728
#define IDD_QQINFO                      729
#define IDD_SERATTR                     730
#define IDI_CHAT                        731
#define IDD_LOGIN1                      731
#define IDB_BITMAP2                     732
#define IDI_BE_CAREFUL1                 732
#define IDB_BITMAP3                     733
#define IDB_BITMAP4                     734
#define IDC_username                    996
#define IDC_userpass                    997
#define IDC_LOGIN                       998
#define IDC_DLLDLG_LOCAL                1000
#define IDC_BUTTON_TXT                  1000
#define IDC_FILENAME                    1000
#define IDC_EXPLORER1                   1000
#define IDC_DLLDLG_REMOTE               1001
#define IDC_SETAGAIN                    1001
#define IDC_BUTTON_CM                   1001
#define IDC_ST_Pause                    1001
#define IDC_VIEW                        1001
#define IDC_LIST_TARGET                 1002
#define IDC_UNLOCK                      1002
#define IDC_BUTTON_EXIT                 1002
#define IDC_MSG_LIST                    1002
#define IDC_TARGET_WEB                  1003
#define IDC_MESSAGE                     1003
#define m_list1                         1003
#define IDC_LOCK                        1003
#define IDC_SENDKEY                     1003
#define IDC_ATTCKPORT                   1004
#define ID_SETLOCK                      1004
#define IDC_PASSWORD                    1004
#define IDC_STATICKEY                   1004
#define IDC_LIST_REMOTE                 1005
#define IDC_THREADNUMS                  1005
#define ID_QUIT                         1005
#define IDC_LIST_LOCAL                  1006
#define IDC_LOCAL_PATH                  1007
#define IDC_HOSTNUMS                    1007
#define IDC_SYSINFO_USECPU              1007
#define IDC_DIRECTORY                   1007
#define IDC_REMOTE_PATH                 1008
#define IDC_SLIDER_THREAD               1008
#define IDC_SYSINFO_USEMEMORY           1008
#define IDC_SURE_PASSWORD               1008
#define IDC_STATIC_REMOTE               1009
#define IDC_ATTACKTIMES                 1009
#define IDC_STATIC_CPU                  1009
#define IDC_CONFIRM                     1010
#define IDC_SLIDER_TIME                 1010
#define IDC_STATIC_MORY                 1010
#define IDC_STARTNAME                   1010
#define IDC_PORT                        1011
#define IDC_LISTEN_PORT                 1011
#define IDC_SPIN_NUM                    1011
#define IDC_OVERWRITE                   1012
#define IDC_CONNECT_MAX                 1012
#define IDC_PORT2                       1012
#define IDC_NEWAUTO                     1012
#define IDC_READONLY                    1012
#define IDC_ADDITION                    1013
#define IDC_SELECTHOST                  1013
#define IDC_COMBO_DNS                   1013
#define IDC_TimeC                       1013
#define IDC_HIDDEN                      1013
#define IDC_IPCOMPASS                   1013
#define IDC_JUMP                        1014
#define IDC_ADDTASK                     1014
#define IDC_SEND_RATE                   1014
#define IDC_OVERWRITE_ALL               1015
#define IDC_COMBO_MODEL                 1015
#define IDC_ADDITION_ALL                1016
#define IDC_STARTVAR                    1016
#define IDC_SPIN_RATE                   1016
#define IDC_JUMP_ALL                    1017
#define IDC_ENDVAR                      1017
#define IDC_CANCEL                      1018
#define IDC_TIPS                        1019
#define IDC_STATIC_TIP                  1020
#define IDC_URL                         1021
#define IDC_EDIT_DECIMAL                1021
#define IDC_EDIT_BUILDLOG               1021
#define IDC_ENCODE                      1022
#define IDC_DNS_STRING                  1022
#define IDC_EDIT_HEX                    1022
#define IDC_INSTALL_SHARE               1022
#define IDC_REMOTE_HOST                 1023
#define IDC_REMOTE_PORT                 1024
#define IDC_STATIC_2                    1024
#define IDC_BTN_PATH                    1024
#define IDC_PROXY_HOST                  1025
#define IDC_STATIC_1                    1025
#define IDC_PROXY_PORT                  1026
#define IDC_STATIC_3                    1026
#define IDC_PROXY_USER                  1027
#define IDC_STATIC_4                    1027
#define IDC_PROXY_PASS                  1028
#define IDC_STATIC_6                    1028
#define IDC_EDIT                        1029
#define IDC_STATIC_7                    1029
#define IDC_BUTTON_TEST_DOWN_RUN_URL    1029
#define IDC_RESETPORT                   1030
#define IDC_STATIC_8                    1030
#define IDC_FOLDERNAME                  1031
#define IDC_STATIC_9                    1031
#define IDC_STATIC_10                   1032
#define IDC_STATIC_11                   1033
#define IDC_LIST_PROCESS                1034
#define IDC_INFOT                       1034
#define IDC_TAB                         1035
#define IDC_EDIT_TIP                    1035
#define IDC_LIST_WINDOWS                1036
#define IDC_STATIC_20                   1036
#define IDC_LIST_DIALUPASS              1037
#define IDC_START_ATTACK                1037
#define IDC_BUILD                       1038
#define IDC_LIST_SERVER                 1038
#define IDC_START_STOP                  1038
#define IDC_LIST_TCP                    1038
#define IDC_EXIT1                       1039
#define IDC_LIST_SOFT                   1039
#define IDC_LIST_4                      1039
#define IDC_CONNECT_AUTO                1040
#define IDC_LIST_3                      1040
#define IDC_GETINFO                     1040
#define IDC_STATIC_VER                  1041
#define IDC_LIST_2                      1041
#define IDC_LIST_1                      1042
#define IDC_ENABLE_HTTP                 1043
#define IDC_CHECK_AUTH                  1048
#define IDC_CHECK_PROXY                 1049
#define IDC_TEST_PROXY                  1050
#define IDC_TEST_MASTER                 1051
#define IDC_SYSTEM_TIPS                 1052
#define IDC_SHOWTIPS                    1052
#define IDC_DISABLE_POPTIPS             1053
#define IDC_SEND_LOCALAUDIO             1054
#define IDC_SAVEAS_DEFAULT              1054
#define IDC_NATIONAL                    1054
#define IDC_LINE                        1055
#define IDC_AUDIO_START                 1055
#define IDC_DAWED_1                     1056
#define IDC_SERVICE_DISPLAYNAME         1058
#define IDC_DAWED_3                     1058
#define IDC_SERVICE_DESCRIPTION         1059
#define IDC_DAWED_4                     1059
#define IDC_EDIT_NAME                   1060
#define IDC_INFO_LIST                   1060
#define IDC_INSTALL_LIST                1060
#define IDC_SLIDER1                     1060
#define IDC_DAWED_5                     1060
#define IDC_EDT_SEARCHSTR               1060
#define IDC_EDIT_DISP                   1061
#define IDC_LIST                        1061
#define IDC_LIST_SEV                    1061
#define IDC_DAWED_6                     1061
#define IDC_EDIT3                       1061
#define IDC_EDIT_KB                     1061
#define IDC_EDT_DESCRIPTION             1061
#define IDC_CK_SUBFORDLE                1061
#define IDC_EDIT_DESC                   1062
#define IDC_LIST_WTS                    1062
#define IDC_DAWED_7                     1062
#define IDC_CK_INFILE                   1062
#define IDC_PATH_NAME                   1063
#define IDC_KEY                         1063
#define IDC_ADMIN                       1063
#define IDC_EXIT_PROXY                  1063
#define IDC_BTN_DNSUPDATE               1063
#define IDC_ZHUOMIAN1                   1063
#define IDC_DAWED_14                    1063
#define IDC_EDIT_URL                    1063
#define IDC_ZHUOMIAN                    1063
#define IDC_BTN_SEARCH                  1063
#define IDC_BUTTON_OK                   1064
#define IDC_CREAT                       1064
#define IDC_IP                          1064
#define IDC_DDOS_ATTACK                 1064
#define IDC_ZHUOMIAN2                   1064
#define IDC_DAWED_9                     1064
#define IDC_PATH                        1065
#define IDC_OPEN3389                    1065
#define IDC_DNSID                       1065
#define IDC_RENWULAN                    1065
#define IDC_EDIT_PATH                   1065
#define IDC_DAWED_8                     1065
#define IDC_RENWULAN1                   1065
#define IDC_STOP                        1066
#define IDC_RADIO1                      1066
#define IDC_DNSPASS                     1066
#define IDC_STOP_FIRE                   1066
#define IDC_RENWULAN2                   1066
#define IDC_OMD3                        1066
#define IDC_EDIT_PORT                   1066
#define IDC_DAWED_10                    1066
#define IDC_GUEST                       1067
#define IDC_RADIO2                      1067
#define IDC_XIANSHIQI                   1067
#define IDC_CMD5                        1067
#define IDC_EDIT_CHATLOG                1067
#define IDC_DAWED_11                    1067
#define IDC_XIANSHIQI1                  1067
#define IDC_CHANGE                      1068
#define IDC_RADIO3                      1068
#define IDC_XIANSHIQI2                  1068
#define IDC_BUTTON_SEND                 1068
#define IDC_DAWED_12                    1068
#define IDC_ADDR                        1069
#define IDC_RADIO4                      1069
#define IDC_PROGRESS_CPU                1069
#define IDC_ZAOYIN                      1069
#define IDC_BUTTON_END                  1069
#define IDC_EDIT_THREAD                 1069
#define IDC_DAWED_15                    1069
#define IDC_CONNECT                     1070
#define IDC_RADIO5                      1070
#define IDC_CHECK_PROCESS               1070
#define IDC_PROGRESS_MEMORY             1070
#define IDC_SHANPING                    1070
#define IDC_EDIT_NEWMSG                 1070
#define IDC_PROGRESS1                   1070
#define IDC_EDIT_THREAD2                1070
#define IDC_CheckOnlineHost             1070
#define IDC_PORTDNS                     1071
#define IDC_DELETE                      1071
#define IDC_CLOSE3389                   1071
#define IDC_DAWED_16                    1071
#define IDC_PORTMAP                     1072
#define IDC_RADIO7                      1072
#define IDC_SAVE                        1072
#define IDC_PROGRESS_3389               1072
#define IDC_GUANGQU                     1072
#define IDC_DISABLE_DRAW                1072
#define IDC_DAWED_13                    1072
#define IDC_GUANGQU1                    1072
#define IDC_LOGIN_USER                  1072
#define IDC_RADIO8                      1073
#define IDC_SELECT_ICO                  1073
#define IDC_FORCE                       1073
#define IDC_GUANGQU2                    1073
#define IDC_DAWED_2                     1073
#define IDC_LOGIN_PASS                  1073
#define IDC_TREE                        1074
#define IDC_RADIO10                     1074
#define IDC_BIG                         1074
#define IDC_ONLINE_INFO_LIST            1074
#define IDC_YINGPAN                     1074
#define IDC_DISABLE_Pifu                1074
#define IDC_RADIO11                     1075
#define IDC_SUIJI                       1075
#define IDC_DAILI                       1075
#define IDC_LAN_CONNECT                 1075
#define IDC_MOUSE                       1075
#define IDC_SKIN_PATH                   1075
#define IDC_MOUSE1                      1075
#define IDC_RADIO12                     1076
#define IDC_KILL                        1076
#define IDC_DAILI_DAILI                 1076
#define IDC_MOUSE2                      1076
#define IDC_CHECK                       1076
#define IDC_SERVICE_LIST                1077
#define IDC_RADIO13                     1077
#define IDC_NOTEPAD                     1077
#define IDC_EDIT_DNSUSER                1077
#define IDC_MENU                        1077
#define IDC_FTPServer                   1077
#define IDC_GDTJ                        1077
#define IDC_BUTTON_TEST_DOWN            1077
#define IDC_FTP                         1077
#define IDC_UPDATE                      1078
#define IDC_CMD                         1078
#define IDC_RADIO_NOIP                  1078
#define IDC_EDIT_DNSPASS                1078
#define IDC_BUTTON_SAVEAS               1078
#define IDC_HFS                         1078
#define IDC_EXIT                        1079
#define IDC_COMBO_GROUP                 1079
#define IDC_CLAC                        1079
#define IDC_RADIO_3322                  1079
#define IDC_EDIT_DNSDOMAIN              1079
#define IDC_SELECTICON                  1079
#define IDC_BUTTON1                     1079
#define IDC_EXIT_LOGIN                  1079
#define IDC_RADIO6                      1080
#define IDC_MSPAINT                     1080
#define IDC_SIGNNOIP                    1080
#define IDC_BUTTON9                     1080
#define IDC_LIST1                       1080
#define IDC_RICHEDIT                    1080
#define IDC_VipName                     1080
#define IDC_LIST_USER                   1080
#define IDC_MSTSC                       1081
#define IDC_SIGN3322                    1081
#define IDC_SIGNNOIP2                   1081
#define IDC_BUTTON6                     1081
#define IDC_VipPass                     1081
#define IDC_LINSTEN_PORT                1082
#define IDC_TASKMGR                     1082
#define ID_UPDATE                       1082
#define IDC_LIST_PROCESST               1082
#define IDC_SIGNNOIP3                   1082
#define IDC_BUTTON10                    1082
#define IDC_MAX_CONNECT                 1083
#define IDC_GPEDIT                      1083
#define IDC_BUTTON11                    1083
#define IDC_CHECK_TIME                  1084
#define IDC_COMPMGMT                    1084
#define IDC_IPUPDATE                    1084
#define IDC_BUTTON7                     1084
#define IDC_EDIT_ADDR                   1084
#define IDC_BUTTON_PREVIS               1084
#define IDC_OPEN_SOUND                  1085
#define IDC_DIRECTX                     1085
#define IDC_GETWAN                      1085
#define IDC_BUTTON8                     1085
#define IDC_EDIT_ADDR2                  1085
#define IDC_CLOSE_TIPS                  1086
#define IDC_SERVICES                    1086
#define IDC_BUTTON12                    1086
#define IDC_EDIT_TIME                   1086
#define IDC_APPLY                       1087
#define IDC_REGEDIT                     1087
#define IDC_ZITI                        1087
#define ID_OPEN3389                     1087
#define IDC_EDIT_TIME2                  1087
#define IDC_SHOW                        1088
#define IDC_EDIT1                       1088
#define IDC_IEXPRESS                    1088
#define IDC_EDIT_SVCNAME                1088
#define IDC_SET                         1088
#define IDC_BUTTON13                    1088
#define IDC_SEND                        1089
#define IDC_SELECT1                     1089
#define IDC_BUTTON14                    1089
#define IDC_GROUP_STYLE                 1089
#define IDC_COMBO_MS                    1089
#define IDC_EDIT2                       1090
#define IDC_EDIT_SCNAME                 1090
#define IDC_STOP1                       1090
#define IDC_BUTTON15                    1090
#define IDC_GROUP_STYLE2                1090
#define IDC_BUTTON_ADD                  1090
#define IDC_SELECT2                     1091
#define IDC_BUTTON4                     1091
#define IDC_LONGIP2                     1091
#define IDC_SHOW1                       1091
#define IDC_BUTTON_DEL                  1091
#define IDC_COMBO_OPERATE               1091
#define IDC_Log                         1091
#define IDC_SYSTEM_TAB                  1092
#define IDC_EDIT_SHELP                  1092
#define IDC_AGREE                       1092
#define IDC_BUTTON_BEGIN                1092
#define IDC_xuanwu                      1092
#define IDC_SELECT3                     1093
#define IDC_LONGPASS2                   1093
#define IDC_DISAGREE                    1093
#define IDC_BUTTON_STOP                 1093
#define IDC_weishi                      1093
#define IDC_EDIT4                       1094
#define IDC_BIAOZHI                     1094
#define IDC_3322                        1094
#define IDC_STATIC_PASS                 1094
#define IDC_Blog                        1094
#define IDC_BUTTON_BEGIN2               1094
#define IDC_CHECK_AUTO                  1094
#define IDM_BLOG                        1094
#define IDC_kugou                       1094
#define IDC_SELECT4                     1095
#define IDC_HUASHENG                    1095
#define IDC_STATIC_USER                 1095
#define IDC_EDIT_ZDY                    1095
#define IDC_FILEATTRIBUTE               1095
#define IDC_liulanqi                    1095
#define IDC_EDIT5                       1096
#define IDC_NOIP                        1096
#define IDC_ME                          1096
#define IDC_RADIO_ANSI                  1096
#define IDC_EDIT_USER                   1096
#define IDC_xunlei                      1096
#define IDC_SELECT5                     1097
#define IDC_RADIO_HEX                   1097
#define IDC_FILESUFFIEX                 1097
#define IDC_TEST                        1097
#define IDC_EDIT_PASS                   1097
#define IDC_tengxun                     1097
#define IDC_BUTTON2                     1098
#define IDC_RADIO_UDP                   1098
#define IDC_BUTTON3                     1099
#define IDC_STATIC_ICON                 1099
#define IDC_RADIO_TCP                   1099
#define IDC_ICO                         1100
#define IDC_LIST2                       1100
#define IDC_BUTTON_STOP2                1100
#define IDC_BUTTON_DEL_SONG             1100
#define IDC_STATIC_TIPS                 1101
#define IDC_ICONS                       1101
#define IDC_DNS1                        1102
#define IDC_SELECTFILE                  1102
#define IDC_OLKEYLOG                    1102
#define IDC_PORT1                       1103
#define IDC_EDIT_TIME1                  1103
#define IDC_CHUANSHU                    1104
#define IDC_STATIC_COUNT                1104
#define IDC_DNS                         1105
#define IDC_AUDIO                       1105
#define IDC_START                       1105
#define IDC_STATIC2                     1105
#define IDC_USER                        1106
#define IDC_SERVICE_DISPLAY             1106
#define IDC_ONLINE_WAY                  1106
#define IDC_CHECK3                      1106
#define IDC_PASS                        1107
#define IDC_SERVICE_DESCRIPT            1107
#define IDC_ONLINE_GROUP                1107
#define IDC_EDIT_S1                     1107
#define www                             1107
#define IDC_GROUPNAME                   1108
#define IDC_INSTALL_WAY                 1108
#define IDC_EDIT_S2                     1108
#define IDC_LOCALIP                     1109
#define IDC_VERSION                     1109
#define IDC_EDIT_PORT2                  1109
#define IDC_EDIT_TEXT                   1110
#define IDC_PROCESS                     1110
#define IDC_SERVICE_NAME                1111
#define IDC_GREEN                       1111
#define IDC_DNS2                        1112
#define IDC_STATIC_ICON1                1113
#define IDC_DEL_MYSELF                  1113
#define IDC_TXT                         1113
#define IDC_STATIC_ICON2                1114
#define IDC_DISABLE_SOUND               1114
#define IDC_STATIC_ICON3                1115
#define IDC_STATIC_ICON4                1116
#define IDC_SPIN1                       1116
#define IDC_EDIT_TITLE                  1117
#define IDC_TEST_MASTER2                1118
#define IDC_IPC                         1119
#define IDC_LONGNECT3                   1119
#define IDC_RADIO14                     1119
#define IDC_UPX                         1120
#define IDC_RADIO15                     1120
#define IDC_BUTTON5                     1121
#define IDC_FTP_IP                      1121
#define IDC_EDIT_ADDR1                  1121
#define IDC_DLLSERVER                   1121
#define IDC_RANDOM                      1122
#define IDC_FILE_PATH                   1122
#define IDC_DLL_NAME                    1122
#define IDC_DLLCLENTVER                 1122
#define IDC_LONGNECT2                   1123
#define IDC_COMBO_MS1                   1123
#define IDC_RANDOM2                     1124
#define IDC_EDIT_PORT1                  1124
#define IDC_Time                        1125
#define IDC_AZZDS                       1125
#define IDC_ENLARGE                     1125
#define IDC_EDIT_THREAD1                1126
#define IDC_SOCKS5                      1127
#define IDC_BUTTON_BEGIN1               1128
#define IDC_BUTTON_STOP1                1129
#define IDC_COMBO_RELEASEPATH           1130
#define IDC_DLLDLG_PROGREBT             1131
#define IDC_PLAYER                      1131
#define IDC_OPEN                        1132
#define IDC_ZKFKZJ                      1135
#define IDC_BUTTON_ADD_SONG             1137
#define IDC_BUTTON_NEXT                 1138
#define IDC_BUTTON_PRE                  1139
#define IDC_PLAYING                     1140
#define IDC_BUTTON_PAUSE                1140
#define IDC_voice                       1142
#define IDC_BUTTON_NEXTS                1143
#define IDC_RADIO16                     1145
#define IDC_RADIO17                     1146
#define IDC_RADIO18                     1147
#define IDC_DLLDLG_PROGRESS             1155
#define IDC_DSBIAOTIXS                  1156
#define IDC_longer                      1156
#define IDC_DLLINUSE_NEWS               1157
#define IDC_alreay                      1157
#define IDC_DLLCLOSE                    1158
#define IDC_DLLDATA_AGAIN               1159
#define IDC_DLLDATA_CONT                1160
#define IDC_VOL                         1160
#define IDC_HTMLVIEW                    1165
#define IDC_CHECK1                      1166
#define IDC_DAWED_17                    1166
#define IDC_EDIT_SEND                   1169
#define IDM_TRANSFERK                   1172
#define IDR_FileToolBar                 1173
#define IDB_FILETB_HOT                  1174
#define IDB_FILETB_DISABLE              1175
#define IDC_FIND_FILE                   1175
#define IDT_REMOTE_GENX                 1176
#define IDC_KBTEST                      1176
#define IDC_KBCHECK                     1177
#define ID_WINDOW_REFLUSH               1178
#define IDC_TAB_MAP                     1178
#define ID_WINDOW_CLOST                 1179
#define IDC_TREE_FRIEND                 1179
#define ID_WINDOW_HIDE                  1180
#define IDC_TREE_GROUP                  1180
#define ID_WINDOW_RETURN                1181
#define IDC_BTN_USER                    1181
#define ID_WINDOW_MAX                   1182
#define IDC_BTN_FRIEND                  1182
#define ID_WINDOW_MIN                   1183
#define IDC_BTN_GROUP                   1183
#define IDC_EDT_STATE                   1184
#define IDC_EDT_SERVICENAME             1185
#define IDC_EDT_DISPLAYNAME             1186
#define IDC_EDT_BINARYPATH              1187
#define IDC_EDT_STARTTYPE               1188
#define IDC_BTN_PREV                    1189
#define IDC_BTN_NEXT                    1190
#define IDC_BTN_GETHOSTS                1191
#define IDC_BTN_SETHOSTS                1192
#define IDC_EDT_HOSTS                   1193
#define IDC_DAWED_18                    1194
#define IDC_DAWED_19                    1195
#define IDM_IBBSOR_A                    1256
#define IDM_IBBSOR_B                    1257
#define IDM_IBBSOR_C                    1258
#define IDM_IBBSOR_D                    1259
#define IDM_IBBSOR_E                    1260
#define IDM_IBBSOR_F                    1261
#define IDM_IBBSOR_G                    1262
#define IDM_IBBSOR_H                    1263
#define IDM_IBBSOR_I                    1264
#define IDM_IBBSOR_J                    1265
#define ID_LOCAL_TOOLBAR                0x5001
#define ID_REMOTE_TOOLBAR               0x5002
#define ID_APP_PWD                      32771
#define IDM_START                       32771
#define IDM_FILEMANAGER                 32772
#define IDM_STOP                        32772
#define IDM_SHUTDOWN                    32773
#define IDM_DELETE_LIST                 32773
#define IDM_REBOOT                      32774
#define IDM_TRANSFER                    32775
#define IDM_RENAME                      32776
#define IDM_DELETE                      32777
#define IDM_NEWFOLDER                   32778
#define IDM_PROPERTY                    32779
#define IDT_LOCAL_PREV                  32780
#define IDT_LOCAL_COPY                  32781
#define IDT_LOCAL_DELETE                32782
#define IDT_LOCAL_VIEW                  32783
#define ID_MENU_DEL                     32783
#define IDT_LOCAL_NEWFOLDER             32784
#define ID_MENU_CREATE                  32784
#define ID_MENU_REF                     32786
#define ID_MENU_START                   32787
#define ID_MENU_STOP                    32788
#define IDT_REMOTE_PREV                 32790
#define IDT_REMOTE_COPY                 32791
#define IDT_REMOTE_DELETE               32792
#define ID_MENU_START_AUTO              32792
#define IDT_REMOTE_NEWFOLDER            32793
#define ID_MENU_START_MANAGER           32793
#define IDT_REMOTE_VIEW                 32794
#define ID_MENU_START_DISABLE           32794
#define IDT_REMOTE_STOP                 32795
#define IDT_LOCAL_STOP                  32797
#define IDM_LOCAL_BIGICON               32798
#define IDM_LOCAL_SMALLICON             32799
#define IDM_LOCAL_LIST                  32800
#define IDM_LOCAL_REPORT                32801
#define IDM_REMOTE_BIGICON              32802
#define IDM_REMOTE_SMALLICON            32803
#define IDM_REMOTE_LIST                 32804
#define ID_MENUITEM_PROXY_MAP           32804
#define IDM_REMOTE_REPORT               32805
#define IDM_SCREENSPY                   32806
#define IDM_DOWNEXEC                    32807
#define IDM_WEBCAM                      32808
#define IDM_REMOVE                      32809
#define IDM_KEYBOARD                    32810
#define IDM_REFRESH                     32811
#define IDM_SYSTEM                      32812
#define IDM_KILLPROCESS                 32813
#define IDM_REFRESHPSLIST               32814
#define IDM_REMOTESHELL                 32815
#define IDM_LOGOFF                      32818
#define IDM_SELECT_ALL                  32820
#define IDM_UNSELECT_ALL                32821
#define IDM_OPEN_URL_SHOW               32825
#define IDM_OPEN_URL_HIDE               32827
#define IDM_CLEANEVENT                  32828
#define IDM_HIDE                        32829
#define IDM_SHOW                        32830
#define IDM_EXIT                        32831
#define IDM_RENAME_REMARK               32832
#define IDM_START_HIDE                  32833
#define IDM_LOCAL_OPEN                  32834
#define IDM_REMOTE_OPEN_SHOW            32836
#define IDM_REMOTE_OPEN_HIDE            32837
#define IDM_AUDIO_LISTEN                32838
#define IDM_DISCONNECT                  32840
#define IDM_ALL_DELETE                  32846
#define IDM_EVENT_SAVE                  32847
#define IDM_EVENT_COPY                  32848
#define IDM_REFSESH_SER                 32849
#define IDM_ADSL_SAVE                   32849
#define IDM_START_SER                   32850
#define IDM_STOP_SER                    32851
#define IDM_DEL_SER                     32852
#define IDM_AUTO_SER                    32853
#define ID_AddGroup                     32853
#define IDM_SERVICE                     32854
#define IDM_HAND_SER                    32854
#define ID_DelGroup                     32854
#define IDM_REGEDIT                     32855
#define IDM_DIS_SER                     32855
#define IDM_SERVER                      32856
#define IDM_SETTING                     32857
#define IDM_BIND                        32858
#define IDM_UPDATE                      32859
#define IDM_BUILD                       32860
#define IDM_INSTALL                     32861
#define IDM_SHOWMSG                     32862
#define IDM_WINDOW                      32864
#define IDM_PROCESS                     32865
#define IDM_CHANGEGROUP                 32866
#define IDM_SKIN_QQ2009                 32867
#define IDM_SKIN_CHINA                  32868
#define IDM_SKIN_BLACK                  32869
#define IDM_SKIN_AERO                   32870
#define IDM_CLOSESKIN                   32871
#define ID_PROXY                        32872
#define IDM_PROXY                       32872
#define IDM_CLEAN_System                32878
#define IDM_CLEAN_Security              32879
#define IDM_CLEAN_Application           32880
#define IDM_SYSINFO                     32886
#define IDM_DDOS                        32887
#define IDM_START_DLLCONART             32888
#define IDC_CUSTOM_SKIN                 32889
#define IDM_START_SHOW                  32890
#define IDM_START_DLLCONGL              32891
#define IDM_START_DLLCONTINUE           32892
#define IDM_IPUPDATE                    32893
#define IDM_NO_START                    32893
#define IDM_START_DLLUPGRADE            32894
#define IDM_CHANGEPASSWORD              32895
#define IDM_DELUSER                     32896
#define IDM_DNSUPDATE                   32896
#define IDM_DISCONNECT_USER             32897
#define IDM_LOGOFF_USER                 32898
#define IDM_Elevate_Privileges          32899
#define IDM_COPY                        32900
#define ID_EXP_ReStart                  32902
#define IDM_ACTIVE_USER                 32904
#define ID_DSA                          32904
#define IDM_DISABLEUSER                 32905
#define IDM_LOCK                        32905
#define IDM_dongjie                     32905
#define IDM_jiedong                     32906
#define IDM_IP                          32912
#define IDM_BEIZHU                      32913
#define IDM_DILIXINXI                   32914
#define IDM_ALL                         32915
#define IDM_IPLIST                      32916
#define IDM_FIND_PROCESS                32917
#define IDM_FINDWINDOWS                 32918
#define IDM_CHAT                        32919
#define IDM_SERMANAGER                  32921
#define IDM_UPDATE_SERVER               32922
#define ID_CHONGZHI                     32923
#define ID_WEB_SERVER                   32924
#define ID_REG                          32926
#define ID_MENUITEM32927                32927
#define ID_MENUITEM32928                32928
#define IDM_MAP                         32930
#define IDM_TOOLS                       32932
#define ID_DIR_RIGHT_ATTRIB             32933
#define IDM_GET_FILEINFO                32934
#define IDM_REFRESHDIALUPASS            32935
#define IDM_SETTING_                    32936
#define IDM_BUILD_                      32937
#define IDM_REGT_DEL                    32938
#define IDM_REGT_CREAT                  32939
#define IDM_TRANSFER_R                  32940
#define IDM_TRANSFER_S                  32941
#define IDM_QQINFO                      32942
#define IDM_RESTART                     32943
#define IDT_TRANSFER_S                  32944
#define IDT_TRANSFER_R                  32945
#define IDM_REGL_DELKEY                 32946
#define IDT_REMOTE_DESKTOP              32946
#define IDM_USE_ADMIN                   32947
#define IDM_REGL_STR                    32948
#define IDT_REMOTE_HOME                 32948
#define IDM_REGL_DWORD                  32949
#define ID_Screen                       32949
#define IDM_REGL_EXSTR                  32950
#define ID_IEQC                         32950
#define IDM_REGL_EDIT                   32951
#define IDM_COMPRESS                    33046
#define IDM_UNCOMPRESS                  33048
#define IDM_KILLDELETE                  40004
#define ID_MENUITEM40015                40015
#define ID_MENUITEM40016                40016
#define ID_PRANK                        40016
#define ID_MENUITEM40017                40017
#define ID_MENUITEM40018                40018
#define ID_MENUITEM40019                40019
#define ID_MENUITEM40020                40020
#define IDM_EVENT_DELETE                42845
#define ID_STAUTSTIP                    59394
#define ID_STAUTSSPEED                  59395
#define ID_STAUTSPORT                   59396
#define ID_STAUTSCOUNT                  59397
#define ID_OS                           59398
#define ID_STAUTSSPEED1                 59399
#define IDC_SETTINGS                    65535
#define IDC_ZITIA                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        739
#define _APS_NEXT_COMMAND_VALUE         32951
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
